INSERT INTO "main"."power_reports" ("id", "district_id", "village_id", "location", "reason", "count", "contact_name", "contact_phone", "created_by", "created_at", "updated_at", "deleted_at", "report_status", "report_restored_at", "taipower_status", "taipower_restored_at", "taipower_note", "taipower_eta_hours", "taipower_support") VALUES (1, 1, 2, 'qwe', 'q12', 12, 'Admin User', '0900000000', 1, NULL, NULL, NULL, 1, NULL, 1, NULL, NULL, NULL, NULL);
INSERT INTO "main"."power_reports" ("id", "district_id", "village_id", "location", "reason", "count", "contact_name", "contact_phone", "created_by", "created_at", "updated_at", "deleted_at", "report_status", "report_restored_at", "taipower_status", "taipower_restored_at", "taipower_note", "taipower_eta_hours", "taipower_support") VALUES (2, 1, 2, 'as', 'dww', 213, 'Admin User', '0900000001', 1, NULL, NULL, NULL, 1, NULL, 0, NULL, 'weqw', 12, 'wqeqw');
INSERT INTO "main"."power_reports" ("id", "district_id", "village_id", "location", "reason", "count", "contact_name", "contact_phone", "created_by", "created_at", "updated_at", "deleted_at", "report_status", "report_restored_at", "taipower_status", "taipower_restored_at", "taipower_note", "taipower_eta_hours", "taipower_support") VALUES (3, 1, 2, 'aswqeqweqw', 'ddde', 12, 'Admin User', '0900000000', 1, NULL, NULL, NULL, 0, NULL, 1, NULL, 'aaa', 22, 'ads');
INSERT INTO "main"."power_reports" ("id", "district_id", "village_id", "location", "reason", "count", "contact_name", "contact_phone", "created_by", "created_at", "updated_at", "deleted_at", "report_status", "report_restored_at", "taipower_status", "taipower_restored_at", "taipower_note", "taipower_eta_hours", "taipower_support") VALUES (4, 1, 1, '123', '123', 12, '里長', '000', 2, NULL, NULL, NULL, 1, NULL, 0, NULL, NULL, NULL, NULL);
INSERT INTO "main"."power_reports" ("id", "district_id", "village_id", "location", "reason", "count", "contact_name", "contact_phone", "created_by", "created_at", "updated_at", "deleted_at", "report_status", "report_restored_at", "taipower_status", "taipower_restored_at", "taipower_note", "taipower_eta_hours", "taipower_support") VALUES (5, 1, 2, 'sad', 'sadsa', 12, '里長', '000', 2, NULL, NULL, NULL, 0, NULL, 0, NULL, NULL, NULL, NULL);

INSERT INTO "main"."water_reports" ("id", "district_id", "village_id", "location", "water_station", "contact_name", "contact_phone", "created_by", "created_at", "updated_at", "deleted_at", "report_status", "report_restored_at", "taiwater_status", "taiwater_restored_at", "taiwater_note", "taiwater_eta_hours", "taiwater_water_station_status", "taiwater_support") VALUES (1, 1, 2, '123', '是', 'Admin User', '0900000000', 1, NULL, NULL, NULL, 1, NULL, 0, NULL, 'qweqw', 12, NULL, 'weqq');
INSERT INTO "main"."water_reports" ("id", "district_id", "village_id", "location", "water_station", "contact_name", "contact_phone", "created_by", "created_at", "updated_at", "deleted_at", "report_status", "report_restored_at", "taiwater_status", "taiwater_restored_at", "taiwater_note", "taiwater_eta_hours", "taiwater_water_station_status", "taiwater_support") VALUES (2, 1, 2, 'ewqeqw', '否', 'Admin User', '0900000000', 1, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "main"."water_reports" ("id", "district_id", "village_id", "location", "water_station", "contact_name", "contact_phone", "created_by", "created_at", "updated_at", "deleted_at", "report_status", "report_restored_at", "taiwater_status", "taiwater_restored_at", "taiwater_note", "taiwater_eta_hours", "taiwater_water_station_status", "taiwater_support") VALUES (3, 1, 2, 'sas', '是', 'Admin User', '0900000000', 1, NULL, NULL, NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL);

INSERT INTO "main"."taiwater_power_reports" ("id", "facility", "pole_number", "electricity_number", "reason", "contact_name", "contact_phone", "created_by", "created_at", "updated_at", "deleted_at", "report_status", "report_restored_at", "taipower_status", "taipower_restored_at", "taipower_note", "taipower_eta_hours", "taipower_support") VALUES (1, '123', '123', '123', '123', 'Admin User', '0900000000', 1, NULL, NULL, NULL, 1, NULL, 0, NULL, '', 2121, '');
INSERT INTO "main"."taiwater_power_reports" ("id", "facility", "pole_number", "electricity_number", "reason", "contact_name", "contact_phone", "created_by", "created_at", "updated_at", "deleted_at", "report_status", "report_restored_at", "taipower_status", "taipower_restored_at", "taipower_note", "taipower_eta_hours", "taipower_support") VALUES (2, '2323', '23', '2324', '232', 'Admin User', '0900000000', 1, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL);
INSERT INTO "main"."taiwater_power_reports" ("id", "facility", "pole_number", "electricity_number", "reason", "contact_name", "contact_phone", "created_by", "created_at", "updated_at", "deleted_at", "report_status", "report_restored_at", "taipower_status", "taipower_restored_at", "taipower_note", "taipower_eta_hours", "taipower_support") VALUES (3, '1243214', '12321', '213', '21312', 'Admin User', '0900000000', 1, NULL, NULL, NULL, 0, NULL, 0, NULL, 'ewre', NULL, '');
